/**
 * Meridian SDK — Node.js
 * Wraps OpenAI (and Anthropic) clients with budget enforcement,
 * cost attribution, and Stripe billing passthrough.
 *
 * Usage:
 *   const ai = Meridian.wrap(new OpenAI(), { apiKey: 'mr_live_...' });
 *   await ai.budgets.set({ customerId: 'cus_acme', daily: 5.00 });
 *   const res = await ai.chat.completions.create({ ... });
 */

import crypto from "crypto";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MeridianConfig {
  apiKey: string;
  baseUrl?: string;         // defaults to https://api.meridian.dev/v1
  environment?: string;     // defaults to 'production'
  flushInterval?: number;   // ms between event flushes, default 2000
  batchSize?: number;       // events per flush, default 100
  onError?: (err: Error) => void;
}

export interface BudgetConfig {
  customerId: string;
  daily?: number;           // USD
  monthly?: number;         // USD
  onBreach?: "block" | "route" | "alert";
  fallbackModel?: string;   // used when onBreach === 'route'
}

export interface LLMEvent {
  eventId: string;          // UUID, generated by SDK
  customerId: string;
  provider: "openai" | "anthropic" | "google";
  model: string;
  feature?: string;
  environment: string;
  inputTokens: number;
  inputTokensCached: number;
  outputTokens: number;
  latencyMs: number;
  metadata?: Record<string, unknown>;
}

export class BudgetExceededError extends Error {
  constructor(
    public readonly customerId: string,
    public readonly limitType: "daily" | "monthly",
    public readonly limitUsd: number,
    public readonly spentUsd: number,
  ) {
    super(
      `Budget exceeded for customer ${customerId}: ` +
      `$${spentUsd.toFixed(4)} spent against $${limitUsd.toFixed(2)} ${limitType} limit`
    );
    this.name = "BudgetExceededError";
  }
}

// ─── Event buffer ─────────────────────────────────────────────────────────────

class EventBuffer {
  private queue: LLMEvent[] = [];
  private timer: ReturnType<typeof setInterval> | null = null;

  constructor(
    private readonly config: MeridianConfig,
    private readonly flush: (events: LLMEvent[]) => Promise<void>,
  ) {
    this.timer = setInterval(() => this.drain(), config.flushInterval ?? 2000);
    // Flush on process exit — best effort
    process.on("beforeExit", () => this.drain());
  }

  push(event: LLMEvent) {
    this.queue.push(event);
    if (this.queue.length >= (this.config.batchSize ?? 100)) {
      this.drain();
    }
  }

  private async drain() {
    if (this.queue.length === 0) return;
    const batch = this.queue.splice(0, this.config.batchSize ?? 100);
    try {
      await this.flush(batch);
    } catch (err) {
      this.config.onError?.(err as Error);
    }
  }

  destroy() {
    if (this.timer) clearInterval(this.timer);
    this.drain();
  }
}

// ─── HTTP client (zero deps — uses native fetch) ──────────────────────────────

class MeridianHTTP {
  private readonly base: string;
  private readonly headers: Record<string, string>;

  constructor(config: MeridianConfig) {
    this.base = (config.baseUrl ?? "https://api.meridian.dev/v1").replace(/\/$/, "");
    this.headers = {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${config.apiKey}`,
      "X-Meridian-SDK": "node/1.0.0",
    };
  }

  async post<T>(path: string, body: unknown): Promise<T> {
    const res = await fetch(`${this.base}${path}`, {
      method: "POST",
      headers: this.headers,
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(`Meridian API ${res.status}: ${text}`);
    }
    return res.json() as Promise<T>;
  }

  async get<T>(path: string): Promise<T> {
    const res = await fetch(`${this.base}${path}`, { headers: this.headers });
    if (!res.ok) throw new Error(`Meridian API ${res.status}`);
    return res.json() as Promise<T>;
  }
}

// ─── Budget manager ───────────────────────────────────────────────────────────

interface BudgetCheckResponse {
  allowed: boolean;
  action: "allow" | "block" | "route";
  fallbackModel?: string;
  limitType?: "daily" | "monthly";
  limitUsd?: number;
  spentUsd?: number;
}

class BudgetManager {
  constructor(private readonly http: MeridianHTTP) {}

  async set(config: BudgetConfig): Promise<void> {
    await this.http.post("/budgets", config);
  }

  async check(customerId: string, estimatedCostUsd?: number): Promise<BudgetCheckResponse> {
    const qs = estimatedCostUsd != null ? `?estimatedCost=${estimatedCostUsd}` : "";
    return this.http.get<BudgetCheckResponse>(`/budgets/${customerId}/check${qs}`);
  }
}

// ─── OpenAI proxy handler ─────────────────────────────────────────────────────

type AnyOpenAI = {
  chat: { completions: { create: (...args: unknown[]) => Promise<unknown> } };
  embeddings: { create: (...args: unknown[]) => Promise<unknown> };
  [key: string]: unknown;
};

function extractCustomerId(params: Record<string, unknown>): string {
  return (params.user as string) ?? (params.metadata as Record<string,string>)?.customer_id ?? "unknown";
}

function extractFeature(params: Record<string, unknown>): string | undefined {
  return (params.metadata as Record<string,string>)?.feature;
}

function uuidv4(): string {
  return crypto.randomUUID();
}

// ─── Main Meridian class ──────────────────────────────────────────────────────

export class Meridian {
  private readonly http: MeridianHTTP;
  private readonly buffer: EventBuffer;
  readonly budgets: BudgetManager;

  private constructor(private readonly config: MeridianConfig) {
    this.http = new MeridianHTTP(config);
    this.buffer = new EventBuffer(config, (events) =>
      this.http.post("/ingest", { events })
    );
    this.budgets = new BudgetManager(this.http);
  }

  /**
   * Wrap an existing OpenAI client.
   * Returns a proxy that intercepts every chat + embeddings call.
   */
  static wrap<T extends AnyOpenAI>(client: T, config: MeridianConfig): T & { budgets: BudgetManager } {
    const meridian = new Meridian(config);
    return meridian.createProxy(client);
  }

  private createProxy<T extends AnyOpenAI>(client: T): T & { budgets: BudgetManager } {
    const meridian = this;

    // Proxy the chat.completions.create method
    const originalCreate = client.chat.completions.create.bind(client.chat.completions);
    client.chat.completions.create = async (...args: unknown[]) => {
      const params = args[0] as Record<string, unknown>;
      const customerId = extractCustomerId(params);
      const feature = extractFeature(params);
      const model = params.model as string;

      // 1. Pre-call budget check
      const check = await meridian.budgets.check(customerId).catch(() => ({
        allowed: true, action: "allow" as const
      }));

      if (check.action === "block") {
        throw new BudgetExceededError(
          customerId,
          check.limitType!,
          check.limitUsd!,
          check.spentUsd!,
        );
      }

      // Route to fallback model if near limit
      const effectiveModel = check.action === "route" && check.fallbackModel
        ? check.fallbackModel
        : model;

      const callParams = { ...params, model: effectiveModel };

      // 2. Execute the LLM call and measure latency
      const t0 = Date.now();
      const response = await originalCreate(callParams);
      const latencyMs = Date.now() - t0;

      // 3. Extract token usage from response
      const usage = (response as Record<string, unknown>).usage as {
        prompt_tokens?: number;
        prompt_tokens_details?: { cached_tokens?: number };
        completion_tokens?: number;
      } | undefined;

      if (usage) {
        meridian.buffer.push({
          eventId: uuidv4(),
          customerId,
          provider: "openai",
          model: effectiveModel,
          feature,
          environment: config.environment ?? "production",
          inputTokens: usage.prompt_tokens ?? 0,
          inputTokensCached: usage.prompt_tokens_details?.cached_tokens ?? 0,
          outputTokens: usage.completion_tokens ?? 0,
          latencyMs,
          metadata: {
            originalModel: model,
            routed: model !== effectiveModel,
            ...(params.metadata as Record<string, unknown> ?? {}),
          },
        });
      }

      return response;
    };

    // Attach the budgets manager to the proxied client
    (client as AnyOpenAI & { budgets: BudgetManager }).budgets = meridian.budgets;

    return client as T & { budgets: BudgetManager };
  }
}

export default Meridian;
